import {zones} from './game-zones.js';
import {HomeStage} from './home-stage.js';
import {voiceInput,releaseVoice,cancelVoice as cancelVoiceInput} from './voice-input.js';
import {GameAudio} from './sound-effects.js';
import {enableMotion,clampZoom,pinchRatio} from './motion-controls.js';
import {prepareMaterials,animatedDuck,animateDuck,decorateProduct,loadProductTextures,texturedUno,splitReachy,animateReachy,animateMiniPi,animateProduct,finishRobotMaterials,animatedMilkBottle} from './product-visuals.js';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import * as CANNON from 'cannon-es';
const $=id=>document.getElementById(id);
let revivalTimer=0;function cancelVoice(){clearTimeout(revivalTimer);cancelVoiceInput();}
const gameAudio=new GameAudio();const playSound=(name,type=0)=>gameAudio.play(name,type);for(const event of ['pointerdown','pointerup','click','keydown'])document.addEventListener(event,()=>gameAudio.unlock(),{capture:true,passive:true});
const products=[
 {key:'so101-black',name:'SO-101 主动臂',source:'TheRobotStudio 官方 URDF / STL',size:2.22},
 {key:'so101-white',name:'SO-101 从动臂',source:'TheRobotStudio 官方 URDF / STL',size:2.22},
 {key:'rebot',name:'reBot Arm B601-RS',source:'Seeed-Projects 官方 URDF / STL',size:2.925},
 {key:'xiao',name:'XIAO ESP32-C3',source:'Seeed Studio 实物 CAD STEP',size:.725},
 {key:'microduck',name:'MicroDuck 机器鸭',source:'Pollen Robotics CAD 网格',size:1.65},
 {key:'reachy-mini',name:'Reachy Mini',source:'Pollen Robotics 官方 GLB',size:2.475,zup:true},
 {key:'recomputer',name:'reComputer Industrial',source:'Seeed Studio 官方 STEP',size:1.6,zup:true},
 {key:'thor',name:'Jetson AGX Thor',source:'NVIDIA 官方开发套件 STEP',size:1.92,zup:true},
 {key:'orin',name:'Jetson Orin Nano',source:'NVIDIA 官方开发套件 STEP',size:1.5,zup:true},
 {key:'watcher',name:'SenseCAP Watcher',source:'Seeed Studio 官方外壳 STEP',size:1.45,zup:true},
 {key:'pi5',name:'树莓派 5',source:'Raspberry Pi 官方 STEP',size:1.65,zup:true},
 {key:'lekiwi',name:'LeKiwi Robot Kit',source:'SIGRobotics 官方 URDF / STL',size:1.8},
 {key:'sts3215',name:'飞特 STS3215 舵机',source:'SO-ARM100 实物尺寸 STL',size:1.05,zup:true},
 {key:'uno-q',name:'Arduino UNO Q',source:'Arduino 官方 STEP',size:1.65,zup:true},
 {key:'dgx-spark',name:'NVIDIA DGX Spark',source:'Wendy 产品三维模型',size:2.1},
 {key:'rdk-x5',name:'地瓜 RDK X5',source:'D-Robotics 官方 STEP',size:1.65,zup:true},
 {key:'mini-pi',name:'高擎动力 Mini Pi',source:'HighTorque Robotics 官方 12DOF URDF',size:2.2},
 {key:'mini-pi-plus',name:'高擎动力 Mini Pi Plus',source:'高擎动力官方 URDF · 米白配色',size:2.3},
 {key:'panthera-ht',name:'高擎动力 Panthera HT',source:'HighTorque 官方 URDF / STL · 金属原色',size:2.7},
 {key:'originbot',name:'古月居 OriginBot',source:'古月居官方 URDF / STL · 产品配色',size:1.9},
 {key:'tonypi',name:'幻尔 TonyPi Pro',source:'社区仿真网格（简化细节）· 原始来源：幻尔 STEP',size:2.3},
 {key:'milk-bottle',name:'高擎动力 奶瓶机器人',source:'用户提供：夹爪奶瓶 STEP · 红黑实物配色',size:2.35,zup:true},
 {key:'prime-q1',name:'启元 Q1',source:'启元官方 Q1 V3 URDF / STL',size:2.45},
 {key:'prime-t1',name:'启元 T1 · 樱漫粉',source:'启元官方 T1 URDF / STL · 双形态变换',size:2.45},
];
const scene=new THREE.Scene();scene.background=new THREE.Color(0x918c82);
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch(e){$('loadtext').textContent='浏览器无法启动 WebGL，请使用支持 WebGL 的浏览器。';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;$('scene').append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-5.1,5.1,7,-7,.1,80);camera.position.set(0,15,5.6);camera.lookAt(0,.3,0);
scene.add(new THREE.HemisphereLight(0xfff4df,0x575850,1.9));const light=new THREE.DirectionalLight(0xfff8ed,2.8);light.position.set(-4,10,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.5,far:28});light.shadow.bias=-.0005;light.shadow.normalBias=.025;scene.add(light);const fill=new THREE.DirectionalLight(0xe9f2ff,1);fill.position.set(6,5,-5);scene.add(fill);
const kitchen=new THREE.Group();scene.add(kitchen);const wok=new THREE.Group();kitchen.add(wok);const POT_STRETCH=1.18;wok.scale.z=POT_STRETCH;
function stoneTexture(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.fillStyle='#8e8980';g.fillRect(0,0,512,512);for(let i=0;i<100000;i++){let x=Math.random()*512,y=Math.random()*512,a=Math.random()*.17;g.fillStyle=Math.random()<.5?`rgba(255,251,238,${a})`:`rgba(35,35,30,${a})`;g.fillRect(x,y,Math.random()*3+1,Math.random()*3+1)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(5,5);t.colorSpace=THREE.SRGBColorSpace;return t}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshStandardMaterial({map:stoneTexture(),roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.12;floor.receiveShadow=true;kitchen.add(floor);
const pts=[new THREE.Vector2(0,-.8),new THREE.Vector2(2.7,-.78),new THREE.Vector2(3.45,-.63),new THREE.Vector2(3.95,-.29),new THREE.Vector2(4.3,.2),new THREE.Vector2(4.48,.65),new THREE.Vector2(4.52,.78),new THREE.Vector2(4.58,.78),new THREE.Vector2(4.6,.67),new THREE.Vector2(4.38,.13),new THREE.Vector2(4.02,-.42),new THREE.Vector2(3.5,-.83),new THREE.Vector2(2.7,-1),new THREE.Vector2(0,-1)];
const pan=new THREE.Mesh(new THREE.LatheGeometry(pts,96),new THREE.MeshStandardMaterial({color:0x343738,metalness:.7,roughness:.63,side:THREE.DoubleSide}));pan.receiveShadow=true;pan.castShadow=true;wok.add(pan);const rim=new THREE.Mesh(new THREE.TorusGeometry(4.53,.043,8,96),new THREE.MeshStandardMaterial({color:0x777d79,metalness:.8,roughness:.4}));rim.rotation.x=Math.PI/2;rim.position.y=.76;wok.add(rim);
for(const z of [-1,1]){const h=new THREE.Mesh(new THREE.TorusGeometry(.58,.085,8,24,Math.PI*1.6),new THREE.MeshStandardMaterial({color:0x31312e,metalness:.65,roughness:.45}));h.rotation.x=Math.PI/2;h.rotation.z=z>0?.63:3.8;h.position.set(0,.45,z*4.62);h.scale.set(1,1.25,1);h.castShadow=true;wok.add(h)}
// Second level: a wide lattice basket on a green maker workbench.
const basket=new THREE.Group();basket.visible=false;kitchen.add(basket);
const basketParts=[];
function basketBar(x,y,z,w,h,d){const g=new THREE.BoxGeometry(w,h,d);g.translate(x,y,z);basketParts.push(g);}
// Tapered deep walls: the mouth is wider than the floor, exposing all four inner faces.
const basketBottom=-.71,basketTop=1.35;
function basketStrut(a,b,width,depth){const from=new THREE.Vector3(...a),to=new THREE.Vector3(...b),delta=to.clone().sub(from);const g=new THREE.BoxGeometry(width,delta.length(),depth);g.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize()));g.translate(...from.add(to).multiplyScalar(.5).toArray());basketParts.push(g);}
for(const side of [-1,1]){
 for(let z=-4.35;z<=4.36;z+=.52)basketStrut([side*3.62,basketBottom,z],[side*4.28,basketTop,z*5.05/4.4],.15,.16);
 for(let x=-3.55;x<=3.56;x+=.5)basketStrut([x,basketBottom,side*4.4],[x*4.28/3.62,basketTop,side*5.05],.16,.15);
 for(const t of [0,.25,.5,.75]){const y=basketBottom+(basketTop-basketBottom)*t,x=3.62+.66*t,z=4.4+.65*t;basketBar(side*x,y,0,.19,.15,z*2);basketBar(0,y,side*z,x*2,.15,.19);}
}
// Wider floor ribs read as molded plastic rather than a flat wire grid.
for(let x=-3.5;x<=3.51;x+=.4)basketBar(x,-.72,0,.16,.16,8.8);
for(let z=-4.3;z<=4.31;z+=.65)basketBar(0,-.74,z,7.24,.13,.16);
const basketMesh=new THREE.Mesh(mergeGeometries(basketParts),new THREE.MeshStandardMaterial({color:0x202623,roughness:.7,metalness:.03}));basketParts.forEach(g=>g.dispose());basketMesh.castShadow=true;basketMesh.receiveShadow=true;basket.add(basketMesh);
// Rounded rectangular lip, with a second underside rail for visible thickness.
const rimShape=new THREE.Shape(),rw=4.28,rd=5.05,rr=.38;
rimShape.moveTo(-rw+rr,-rd);rimShape.lineTo(rw-rr,-rd);rimShape.quadraticCurveTo(rw,-rd,rw,-rd+rr);rimShape.lineTo(rw,rd-rr);rimShape.quadraticCurveTo(rw,rd,rw-rr,rd);rimShape.lineTo(-rw+rr,rd);rimShape.quadraticCurveTo(-rw,rd,-rw,rd-rr);rimShape.lineTo(-rw,-rd+rr);rimShape.quadraticCurveTo(-rw,-rd,-rw+rr,-rd);
const rimCurve=new THREE.CatmullRomCurve3(rimShape.getPoints(16).map(p=>new THREE.Vector3(p.x,basketTop,p.y)),true);
const basketLip=new THREE.Mesh(new THREE.TubeGeometry(rimCurve,160,.16,8,true),new THREE.MeshStandardMaterial({color:0x353c38,roughness:.42,metalness:.08}));basketLip.castShadow=true;basketLip.receiveShadow=true;basket.add(basketLip);
for(const side of [-1,1]){const grip=new THREE.Mesh(new THREE.BoxGeometry(1.7,.22,.35),basketLip.material);grip.position.set(0,basketTop+.03,side*5.05);grip.castShadow=true;basket.add(grip);}
const stoneMaterial=floor.material;
function benchTexture(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.fillStyle='#216e50';g.fillRect(0,0,512,512);g.strokeStyle='#80b49a22';g.lineWidth=1;for(let i=0;i<=512;i+=32){g.beginPath();g.moveTo(i,0);g.lineTo(i,512);g.moveTo(0,i);g.lineTo(512,i);g.stroke();}for(let i=0;i<6500;i++){g.fillStyle=i%2?'#d9f4db08':'#002f240c';g.fillRect(Math.random()*512,Math.random()*512,1,1);}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(6,6);return t;}
const benchMaterial=new THREE.MeshStandardMaterial({map:benchTexture(),roughness:.83});
const benchLabel=document.createElement('div');benchLabel.className='bench-label';benchLabel.hidden=true;benchLabel.textContent='';$('game').append(benchLabel);
const world=new CANNON.World({gravity:new CANNON.Vec3(0,-12,0),allowSleep:true});world.broadphase=new CANNON.SAPBroadphase(world);world.solver.iterations=8;world.defaultContactMaterial.friction=.48;world.defaultContactMaterial.restitution=.08;
let ground=new CANNON.Body({mass:0,shape:new CANNON.Plane()});ground.quaternion.setFromEuler(-Math.PI/2,0,0);ground.position.y=-.63;world.addBody(ground);const roundWalls=[],basketWalls=[];for(let i=0;i<32;i++){let a=i/32*Math.PI*2,b=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(.6,2,.17))});b.position.set(Math.sin(a)*4.05,.6,Math.cos(a)*4.05*POT_STRETCH);b.quaternion.setFromEuler(0,Math.atan2(Math.sin(a),Math.cos(a)/POT_STRETCH),0);world.addBody(b);roundWalls.push(b)}
for(const [x,z,hx,hz] of [[-4.35,0,.14,5.3],[4.35,0,.14,5.3],[0,-5.2,4.5,.14],[0,5.2,4.5,.14]]){const wall=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(hx,2,hz))});wall.position.set(x,.6,z);wall.collisionFilterMask=0;world.addBody(wall);basketWalls.push(wall);}
function setLevelScene(n){$('game').dataset.level=String(n);const rectangular=n===2;wok.visible=!rectangular;basket.visible=rectangular;floor.material=rectangular?benchMaterial:stoneMaterial;benchLabel.hidden=!rectangular;roundWalls.forEach(b=>b.collisionFilterMask=rectangular?0:-1);basketWalls.forEach(b=>b.collisionFilterMask=rectangular?-1:0);basket.position.y=0;basket.rotation.set(0,0,0);}
const templates=[],thumbnails=[];let items=[],tray=[],holding=[],removed=0,total=72,level=1,remaining=600,status='loading',paused=false,locked=false,uses={remove:2,gather:2,shuffle:3},lastT=0,timerAccum=0,messageTimer,inspecting=false,inspectObj,inspectIndex=0,dragStart,dragLast,moved=false,ready=false;
let pendingDeck=[],pourElapsed=0,pourClock=0,settleTime=0,tossClock=0,lastToss=-Infinity,inspectZoom=1,motionEnabled=false;const activePointers=new Map();let pinchStart=0,pinchStartZoom=1;
let homeStage=null,catalogFromHome=false,runMode='campaign';
$('titleLogo').src=window.SEEED_TITLE_DATA?.products||'assets/titles/title-products.png';
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
function bake(gltf,p){if(['prime-q1','prime-t1','originbot','tonypi'].includes(p.key)){if(p.key.startsWith('prime-'))finishRobotMaterials(gltf.scene,p.key);return animatedDuck(gltf,p.size);}if(p.key==='uno-q')return texturedUno(gltf,p.size);if(p.key==='dgx-spark')return animatedDuck(gltf,p.size);if(p.key==='mini-pi-plus')return animatedDuck(gltf,p.size);if(p.key==='mini-pi')return animatedDuck(gltf,p.size);if(p.key==='microduck')return animatedDuck(gltf,p.size);const root=gltf.scene;prepareMaterials(root,p.key);root.updateMatrixWorld(true);const parts=[];root.traverse(n=>{if(!n.isMesh||!n.geometry.attributes.position)return;let g=n.geometry.clone();if(g.index)g=g.toNonIndexed();g.applyMatrix4(n.matrixWorld);let rgb=new Float32Array(g.attributes.position.count*3);const materials=Array.isArray(n.material)?n.material:[n.material];let base=materials[0]?.color||new THREE.Color(.7,.7,.7);const sourceColors=g.attributes.color;for(let i=0;i<g.attributes.position.count;i++){if(sourceColors){rgb[i*3]=sourceColors.getX(i)*base.r;rgb[i*3+1]=sourceColors.getY(i)*base.g;rgb[i*3+2]=sourceColors.getZ(i)*base.b}else base.toArray(rgb,i*3);}for(const group of sourceColors?[]:g.groups){const col=materials[group.materialIndex]?.color||base;for(let i=group.start;i<Math.min(group.start+group.count,g.attributes.position.count);i++)col.toArray(rgb,i*3)}g.setAttribute('color',new THREE.BufferAttribute(rgb,3));for(const k of Object.keys(g.attributes))if(!['position','normal','color'].includes(k))g.deleteAttribute(k);if(!g.attributes.normal)g.computeVertexNormals();g.clearGroups();parts.push(g)});if(!parts.length)throw Error(p.name+' 模型为空');const geo=mergeGeometries(parts);parts.forEach(g=>g.dispose());if(p.zup)geo.rotateX(-Math.PI/2);geo.computeBoundingBox();const sz=geo.boundingBox.getSize(new THREE.Vector3()),center=geo.boundingBox.getCenter(new THREE.Vector3());geo.translate(-center.x,-center.y,-center.z);const scale=p.size/Math.max(sz.x,sz.y,sz.z);geo.scale(scale,scale,scale);geo.computeBoundingBox();const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.45,metalness:.2,side:THREE.DoubleSide}));mesh.castShadow=true;mesh.receiveShadow=p.key!=='pi5';mesh.userData.half=geo.boundingBox.getSize(new THREE.Vector3()).multiplyScalar(.5);return p.key==='milk-bottle'?animatedMilkBottle(mesh):p.key==='reachy-mini'?splitReachy(mesh):decorateProduct(mesh,p.key)}
function thumbnail(model){const s=new THREE.Scene();s.add(new THREE.HemisphereLight(0xffffff,0x69715f,3));let l=new THREE.DirectionalLight(0xffffff,4);l.position.set(-3,5,5);s.add(l);const obj=model.clone();obj.rotation.y=-.5;s.add(obj);let cam=new THREE.PerspectiveCamera(32,1,.01,20);cam.position.set(2.6,2.1,3.2);cam.lookAt(0,0,0);const oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(160,160,false);renderer.setClearColor(0x000000,0);renderer.render(s,cam);const url=renderer.domElement.toDataURL('image/png');renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);renderer.setClearColor(0x918c82,1);return url}
async function load(){try{await loadProductTextures();const loader=new GLTFLoader();const requested=new URLSearchParams(location.search).get('model');const indices=products.map((_,i)=>i).filter(i=>!requested||products[i].key===requested);if(!indices.length)throw Error('未找到该产品');for(const i of indices){$('loadtext').textContent=`正在加载 ${products[i].name}（${i+1}/${products.length}）`;const gltf=await loader.loadAsync(window.SEEED_MODEL_DATA?.[products[i].key]||`assets/models/${products[i].key}.glb`);templates[i]=bake(gltf,products[i]);thumbnails[i]=thumbnail(templates[i]);$('loadbar').style.width=((i+1)/products.length*100)+'%'}ready=true;resize();requestAnimationFrame(frame);let chosenLevel=1;if(!requested){await waitForEntry();chosenLevel=await chooseHome();}$('loading').hidden=true;if(requested){status='playing';$('catalogButton').click()}else start(chosenLevel)}catch(e){console.error(e);$('loadtext').textContent='模型加载失败：'+e.message;const b=document.createElement('button');b.className='gold';b.textContent='重新加载';b.onclick=()=>location.reload();document.querySelector('.loadbox').append(b)}}
function waitForEntry(){
 status='ready';$('loadtext').textContent='加载完成，准备好一起抓了吗？';
 const button=document.createElement('button');button.id='enterGame';button.className='gold';button.textContent='进入游戏';
 document.querySelector('.loading-progress').append(button);
 return new Promise(resolve=>{button.addEventListener('click',()=>{
  button.disabled=true;
  // Start audible playback synchronously inside the user's click.
  gameAudio.musicWanted=true;gameAudio.unlock();
  button.remove();resolve();
 },{once:true});button.focus();});
}
const homeIconKeys=['campaign','stew','catalog',...Object.keys(zones)];
async function chooseHome(){
 status='home';paused=true;gameAudio.music(!document.hidden);clearSelection();clearTimeout(messageTimer);$('message').classList.remove('show');$('overlay').hidden=true;$('loading').hidden=false;$('game').classList.add('home');resize();
 const menu=$('homeMenu');menu.hidden=false;menu.innerHTML=['闯关','乱炖','图鉴',...Object.values(zones).map(z=>z.name)].map((name,i)=>`<button class="home-action ${i>2?'zone-action':''}" data-zone="${i>2?homeIconKeys[i]:''}" aria-label="${name}"><img class="home-icon" src="${window.SEEED_ICON_DATA?.[homeIconKeys[i]]||`assets/icons/${homeIconKeys[i]}.png`}" alt="" draggable="false"><b>${name}</b></button>`).join('');
 homeStage?.dispose();homeStage=new HomeStage(renderer,$('homeHero'),templates,products,type=>playSound('select',type));
 const buttons=menu.querySelectorAll('button');buttons[2].onclick=()=>{$('catalogButton').click();};
 const selected=await new Promise(resolve=>{for(const [i,n]of [1,3].entries())buttons[i].onclick=()=>{buttons.forEach(b=>b.disabled=true);gameAudio.unlock();resolve(n);};for(const [i,key]of Object.keys(zones).entries())buttons[i+3].onclick=()=>{buttons.forEach(b=>b.disabled=true);gameAudio.unlock();resolve(key);};});
 homeStage.dispose();homeStage=null;menu.hidden=true;$('game').classList.remove('home');$('loading').hidden=true;renderer.setClearColor(0x918c82,1);resize();return selected;
}
$('homeButton').onclick=async()=>{cancelVoice();start(await chooseHome());};
function resize(){const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h,false);const half=4.75;camera.left=-half;camera.right=half;camera.top=half*h/w;camera.bottom=-camera.top;camera.updateProjectionMatrix()}
new ResizeObserver(resize).observe($('scene'));
function spawn(type,id){const mesh=templates[type].clone();const half=mesh.userData.half;const body=new CANNON.Body({mass:.45,shape:new CANNON.Box(new CANNON.Vec3(Math.max(.13,half.x*.85),Math.max(.12,half.y*.85),Math.max(.13,half.z*.85))),linearDamping:.34,angularDamping:.55,sleepSpeedLimit:.15,sleepTimeLimit:.7});const a=id*2.39996,r=Math.sqrt((id%18+.5)/18)*2.9;body.position.set(Math.cos(a)*r,Math.min(7,2.8+Math.max(0,...items.map(it=>it.body.position.y))),Math.sin(a)*r*POT_STRETCH);body.quaternion.setFromEuler(Math.random()*2.7,Math.random()*Math.PI*2,Math.random()*2.7);if(level===1){body.position.set(((id%4)-1.5)*1.65,4, (Math.floor(id/4)-1)*1.7);body.quaternion.setFromEuler(-.2,(Math.random()-.5)*.6,0)}if(level===2||!!zones[runMode]){body.position.x=((id%6)-2.5)*1.23+(Math.random()-.5)*.3;body.position.z=(Math.floor(id/6)%7-3)*1.27+(Math.random()-.5)*.3;}const item={id,type,mesh,body};mesh.position.copy(body.position);mesh.quaternion.copy(body.quaternion);mesh.userData.item=item;world.addBody(body);scene.add(mesh);return item}
function start(n=1){juiceCombo=0;lastClearAt=0;cancelVoice();clearSelection();items.forEach(i=>{scene.remove(i.mesh);world.removeBody(i.body)});items=[];tray=[];holding=[];removed=0;runMode=Object.hasOwn(zones,n)?n:'campaign';level=zones[runMode]?3:Math.max(1,Math.min(3,n));setLevelScene(zones[runMode]?2:level);const types=zones[runMode]?products.map((p,i)=>zones[runMode].keys.includes(p.key)?i:-1).filter(i=>i>=0):level===1?[0,1,4,3]:level===2?['so101-black','so101-white','microduck','dgx-spark','pi5','lekiwi','reachy-mini'].map(key=>products.findIndex(p=>p.key===key)):products.map((_,i)=>i);const copies=zones[runMode]?24:level===1?3:6;total=types.length*copies;remaining=600;timerAccum=0;uses={remove:2,gather:2,shuffle:3};status='pouring';paused=false;locked=false;let deck=[];types.forEach(type=>{for(let j=0;j<copies;j++)deck.push(type)});shuffleArray(deck);pendingDeck=deck;pourElapsed=0;pourClock=0;settleTime=0;tossClock=0;wok.position.y=0;wok.rotation.set(0,0,0);$('overlay').hidden=true;$('level').innerHTML=`<span class="level-star" aria-hidden="true">★</span><span class="level-number">${zones[runMode]?zones[runMode].badge:String(level).padStart(2,'0')}</span>`;$('level').setAttribute('aria-label',zones[runMode]?zones[runMode].name:`第 ${level} 关`);$('time').textContent='10:00';update();$('hoverName').textContent='';$('scene').setAttribute('aria-label',`空锅准备中，0 / ${total} 件产品`);message(zones[runMode]?zones[runMode].name+'，产品正在入篮…':level===2?'工作台准备好，产品正在入篮…':'空锅准备好，产品正在入锅…')}
function shuffleArray(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function syncMeshes(){for(const i of items){const h=i.mesh.userData.half;const margin=Math.min(1.3,Math.hypot(h.x,h.z)*.85);if(level===2||!!zones[runMode]){for(const [axis,extent] of [['x',3.55+Math.min(1,Math.max(0,(i.body.position.y+.65)/2))*.65],['z',4.33+Math.min(1,Math.max(0,(i.body.position.y+.65)/2))*.65]]){const limit=extent-margin;if(Math.abs(i.body.position[axis])>limit){const sign=Math.sign(i.body.position[axis]);i.body.position[axis]=sign*limit;if(i.body.velocity[axis]*sign>0)i.body.velocity[axis]*=-.2;}}}else{const limit=4.25-margin;const r=Math.hypot(i.body.position.x,i.body.position.z/POT_STRETCH);if(r>limit){const nx=i.body.position.x/r,nz=i.body.position.z/r;i.body.position.x=nx*limit;i.body.position.z=nz*limit;const outward=i.body.velocity.x*nx+i.body.velocity.z*nz;if(outward>0){i.body.velocity.x-=outward*nx*1.2;i.body.velocity.z-=outward*nz*1.2;}}}if(i.body.position.y<-1){i.body.position.y=.2;i.body.velocity.y=0;}i.mesh.position.copy(i.body.position);i.mesh.quaternion.copy(i.body.quaternion);}}
function tickPour(dt){pourElapsed+=dt;pourClock+=dt;if(pourElapsed>.45){const interval=level===1?.18:.065;while(pourClock>=interval&&pendingDeck.length){pourClock-=interval;const type=pendingDeck.shift();playSound('drop',type);items.push(spawn(type,total-pendingDeck.length-1));$('scene').setAttribute('aria-label',`正在入锅，${items.length} / ${total} 件产品`);}if(!pendingDeck.length){settleTime+=dt;if(settleTime>1.4){status='playing';$('scene').setAttribute('aria-label',`真实三维产品堆叠，共 ${total} 件产品，点击产品进行收集`);update();message(level===1?'入门关：4 种产品，每种 3 件':level===2?'精选关：7 种产品，每种 6 件':zones[runMode]?zones[runMode].name+'：收集本区全部产品！':'乱炖：全部产品到齐，开始抓！');}}}}
function tossPan(strength=1){if(!canPlay()||performance.now()-lastToss<850)return;lastToss=performance.now();playSound('toss');tossClock=.6;for(const it of items){it.body.wakeUp();const x=it.body.position.x,z=it.body.position.z;it.body.velocity.y=Math.min(4.4,2.4+strength);it.body.velocity.x=-x*.22+(Math.random()-.5)*strength;it.body.velocity.z=-z*.22+(Math.random()-.5)*strength;it.body.angularVelocity.set((Math.random()-.5)*2.8, (Math.random()-.5)*2,(Math.random()-.5)*2.8);}message('颠一下，翻出新产品！');}
let motionPending=false,motionAttempted=false;
async function autoMotion(){if(motionEnabled||motionPending||motionAttempted)return;motionPending=true;motionAttempted=true;motionEnabled=await enableMotion(tossPan,()=>{});motionPending=false;}
if(typeof window.DeviceMotionEvent?.requestPermission!=='function')autoMotion();
document.addEventListener('pointerdown',autoMotion,{passive:true});


function update(){const e=$('tray');e.innerHTML='';for(let k=0;k<7;k++){let slot=document.createElement('div');slot.className='slot';if(tray[k]){let img=document.createElement('img');img.src=thumbnails[tray[k].type];img.alt=products[tray[k].type].name;slot.append(img)}e.append(slot)}e.classList.toggle('danger',tray.length>=5);$('holding').innerHTML='';for(const it of holding){const b=document.createElement('button');b.title='取回 '+products[it.type].name;b.setAttribute('aria-label',b.title);b.innerHTML=`<img src="${thumbnails[it.type]}" alt="${products[it.type].name}">`;b.onclick=()=>select(it,true);$('holding').append(b)}for(const key of ['remove','gather','shuffle']){$(key+'Count').textContent=uses[key];$(key).disabled=uses[key]<=0||!['playing','pouring'].includes(status)||locked||(key==='remove'&&(!tray.length||holding.length>0))||(key==='shuffle'&&!items.length)}}
function detach(item){scene.remove(item.mesh);world.removeBody(item.body);items=items.filter(i=>i!==item)}
function canPlay(){return ready&&['playing','pouring'].includes(status)&&!paused&&!locked&&!inspecting}
function select(item,fromHolding=false){if(!canPlay()||tray.length>=7)return;const pickupPoint=fromHolding?null:productScreenPoint(item);if(fromHolding){holding=holding.filter(i=>i!==item)}else detach(item);let idx=tray.findLastIndex(x=>x.type===item.type);tray.splice(idx<0?tray.length:idx+1,0,item);$('hoverName').textContent=products[item.type].name;resolve();pickupJuice(item,pickupPoint)}
function resolve(){const counts=new Map();tray.forEach(i=>counts.set(i.type,(counts.get(i.type)||0)+1));const triple=[...counts].find(([,n])=>n>=3);if(triple){locked=true;update();Array.from($('tray').children).forEach((s,i)=>{if(tray[i]?.type===triple[0])s.classList.add('clearing')});setTimeout(()=>{let n=0;tray=tray.filter(i=>{if(i.type===triple[0]&&n<3){n++;return false}return true});removed+=3;locked=false;playSound('clear',triple[0]);clearJuice();checkEnd();update()},240)}else{checkEnd();update()}}
function checkEnd(){if(removed===total){status='won';showDialog('这一锅，抓完了！',`成功收集 ${total} 件产品\n用时 ${Math.floor((600-remaining)/60)} 分 ${(600-remaining)%60} 秒`,level===3?'再来一锅':'下一关')}else if(tray.length>=7){playSound('full');status='lost';showDialog('槽位满了！',`已经消除 ${removed} / ${total} 件产品\n试试优先收集槽里已有的产品。`,'重新开始')}}
function showDialog(title,text,action='继续游戏'){cancelVoice();clearSelection();paused=true;$('revive').hidden=status!=='lost';$('reviveResult').textContent='';$('reviveStatus').textContent='';$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('resumeLabel').textContent=action;$('resume').hidden=status==='lost';$('overlay').dataset.mode=status;$('reviveBenefit').textContent=remaining===0?'续时 3 分钟 · 继续这一局':'清空槽位 · 继续这一局';$('voice').disabled=false;$('overlay').hidden=false;(status==='lost'?$('voice'):$('resume')).focus()}
$('pause').onclick=()=>{if(!ready||locked||status==='home')return;showDialog('暂停一下',`${zones[runMode]?zones[runMode].name:`第 ${level} 关`} · 已消除 ${removed} / ${total}\n按住滑动挑选，松手抓取；颠手机翻锅。\n三个相同产品自动消除，槽满或超时失败。`)};
$('resume').onclick=()=>{cancelVoice();if(status==='won')start(zones[runMode]?runMode:level+1);else if(status==='lost')start(zones[runMode]?runMode:level);else{paused=false;$('overlay').hidden=true}};$('restart').onclick=()=>start(zones[runMode]?runMode:level);
$('remove').onclick=()=>{if(!canPlay()||uses.remove<=0||!tray.length||holding.length)return;playSound('remove');holding=tray.splice(0,3);uses.remove--;update();message('已移出，点击暂存产品可取回')};
$('gather').onclick=()=>{if(!canPlay()||uses.gather<=0)return;const counts=products.map((_,t)=>({t,n:tray.filter(i=>i.type===t).length})).sort((a,b)=>b.n-a.n);let choice=counts.find(({t,n})=>n<3&&items.filter(i=>i.type===t).length+holding.filter(i=>i.type===t).length>=3-n);if(!choice){message('没有可凑齐的产品');return}let need=3-choice.n;if(tray.length+need>9){message('先用移出，腾出一点空间');return}playSound('gather');uses.gather--;const t=choice.t;for(let i=0;i<need;i++){let it=holding.find(x=>x.type===t)||items.find(x=>x.type===t);if(holding.includes(it))holding=holding.filter(x=>x!==it);else detach(it);tray.push(it)}tray.sort((a,b)=>a.type-b.type);resolve()};
$('shuffle').onclick=()=>{if(!canPlay()||uses.shuffle<=0||!items.length)return;playSound('shuffle');uses.shuffle--;const positions=shuffleArray(items.map(i=>({x:i.body.position.x,z:i.body.position.z})));items.forEach((i,n)=>{i.body.wakeUp();i.body.position.set(positions[n].x,1.3+Math.floor(n/20)*1.15,positions[n].z);i.body.velocity.set((Math.random()-.5)*2,3,(Math.random()-.5)*2);i.body.angularVelocity.set(Math.random()*4,Math.random()*4,Math.random()*4)});update();message('打乱一下，换个角度再抓！')};
function message(s){clearTimeout(messageTimer);$('message').textContent=s;$('message').classList.add('show');messageTimer=setTimeout(()=>$('message').classList.remove('show'),1800)}
let juiceCombo=0,lastClearAt=0;
function productScreenPoint(item){const pos=item.mesh.getWorldPosition(new THREE.Vector3()).project(camera),r=renderer.domElement.getBoundingClientRect(),g=$('game').getBoundingClientRect();return{x:r.left-g.left+(pos.x+1)*r.width/2,y:r.top-g.top+(1-pos.y)*r.height/2};}
function pickupJuice(item,point){const slotIndex=tray.indexOf(item),slot=$('tray').children[slotIndex];if(!slot)return;slot.animate([{transform:'scale(.88)'},{transform:'scale(1.12)',offset:.6},{transform:'scale(1)'}],{duration:280,easing:'ease-out'});if(!point||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=slot.getBoundingClientRect(),g=$('game').getBoundingClientRect(),fly=document.createElement('img');fly.className='pickup-flight';fly.src=thumbnails[item.type];fly.alt='';fly.style.left=point.x+'px';fly.style.top=point.y+'px';$('game').append(fly);const dx=r.left-g.left+r.width/2-point.x,dy=r.top-g.top+r.height/2-point.y;const a=fly.animate([{transform:'translate(-50%,-50%) scale(1)',opacity:1},{transform:`translate(calc(-50% + ${dx*.45}px),calc(-50% + ${dy*.4-30}px)) scale(1.25)`,opacity:1,offset:.45},{transform:`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px)) scale(.55)`,opacity:0}],{duration:260,easing:'cubic-bezier(.2,.65,.3,1)'});a.finished.finally(()=>fly.remove());}
function clearJuice(){const now=performance.now();juiceCombo=now-lastClearAt<4200?Math.min(juiceCombo+1,9):1;lastClearAt=now;const g=$('game').getBoundingClientRect(),r=$('tray').getBoundingClientRect(),x=r.left-g.left+r.width/2,y=r.top-g.top+r.height/2;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(!reduced){$('tray').animate([{transform:'scale(1)'},{transform:'scale(1.035) translateY(-4px)',offset:.35},{transform:'scale(1)'}],{duration:300});for(let i=0;i<30;i++){const el=document.createElement('i');el.className='juice-spark';const angle=Math.random()*Math.PI*2,d=35+Math.random()*110;el.style.cssText=`left:${x+(Math.random()-.5)*r.width*.6}px;top:${y}px;background:${['#ffc83d','#f58c66','#9bcc72','#fff6c2'][i%4]};--jx:${Math.cos(angle)*d}px;--jy:${-30-Math.random()*120}px;--jr:${Math.random()*260}deg`;$('game').append(el);el.addEventListener('animationend',()=>el.remove(),{once:true});}}
 const label=document.createElement('div');label.className='juice-label';label.textContent=juiceCombo>1?`${juiceCombo} 连消！`:'三消！';label.style.top=(r.top-g.top-30)+'px';$('game').append(label);label.addEventListener('animationend',()=>label.remove(),{once:true});navigator.vibrate?.(juiceCombo>1?[20,25,40]:[18,20,28]);
}
function confetti(){for(let i=0;i<18;i++){let el=document.createElement('i');el.className='confetti';el.style.cssText=`background:${['#ffdf41','#70d844','#fff6d0'][i%3]};--dx:${Math.random()*260-130}px;--dy:${-50-Math.random()*190}px`;$('game').append(el);setTimeout(()=>el.remove(),850)}}
function getHit(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);let hit=ray.intersectObjects(items.map(i=>i.mesh),true)[0]?.object;while(hit&&!hit.userData.item)hit=hit.parent;return hit?.userData.item}
let selectedItem=null,selectionShells=[],selectionTimer=0;
const goldOutline=new THREE.MeshBasicMaterial({color:0xffc928,side:THREE.BackSide,depthWrite:false});
function clearSelection(){clearTimeout(selectionTimer);selectionTimer=0;for(const shell of selectionShells)shell.parent?.remove(shell);selectionShells=[];selectedItem=null;}
function highlight(item){if(item===selectedItem)return;clearSelection();if(!item)return;selectedItem=item;playSound('select');const meshes=[];item.mesh.traverse(n=>{if(n.isMesh)meshes.push(n)});for(const n of meshes){const shell=new THREE.Mesh(n.geometry,goldOutline);shell.scale.setScalar(1.045);shell.raycast=()=>{};shell.renderOrder=2;n.add(shell);selectionShells.push(shell);}$('hoverName').textContent=products[item.type].name;}
function selectionBurst(item){const pos=item.mesh.getWorldPosition(new THREE.Vector3()).project(camera),r=renderer.domElement.getBoundingClientRect(),g=$('game').getBoundingClientRect();for(let i=0;i<24;i++){const el=document.createElement('i');el.className='selection-particle';const a=Math.random()*Math.PI*2,d=25+Math.random()*65;el.style.cssText=`left:${r.left-g.left+(pos.x+1)*r.width/2}px;top:${r.top-g.top+(1-pos.y)*r.height/2}px;--dx:${Math.cos(a)*d}px;--dy:${Math.sin(a)*d}px`;$('game').append(el);setTimeout(()=>el.remove(),650);}navigator.vibrate?.(35);}
renderer.domElement.addEventListener('pointerdown',e=>{if(selectionTimer&&selectedItem&&canPlay()){const previous=selectedItem;clearSelection();select(previous);}activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});renderer.domElement.setPointerCapture(e.pointerId);if(inspecting&&activePointers.size===2){pinchStart=pinchRatio([...activePointers.values()]);pinchStartZoom=inspectZoom;moved=true;dragStart=null;}else{dragStart={x:e.clientX,y:e.clientY};dragLast={...dragStart};moved=false;if(canPlay()&&activePointers.size===1)highlight(getHit(e));}});
renderer.domElement.addEventListener('pointermove',e=>{if(activePointers.has(e.pointerId))activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(inspecting&&activePointers.size>=2){const d=pinchRatio([...activePointers.values()]);if(pinchStart>0)setInspectZoom(pinchStartZoom*d/pinchStart);return;}if(!dragStart)return;const dx=e.clientX-dragLast.x,dy=e.clientY-dragLast.y;dragLast={x:e.clientX,y:e.clientY};if(Math.hypot(e.clientX-dragStart.x,e.clientY-dragStart.y)>10)moved=true;if(inspecting&&inspectObj){inspectObj.rotation.y+=dx*.012;inspectObj.rotation.x+=dy*.012;}else if(canPlay()&&activePointers.size===1)highlight(getHit(e));});
function releasePointer(e){const wasPinch=activePointers.size>1;activePointers.delete(e.pointerId);if(e.type==='pointerup'&&!wasPinch&&!inspecting&&canPlay()){const hit=getHit(e);highlight(hit);if(hit){selectionBurst(hit);selectionTimer=setTimeout(()=>{const target=selectedItem;clearSelection();if(target&&items.includes(target))select(target);},150);}}else clearSelection();dragStart=null;pinchStart=0;if(activePointers.size===1){const pos=[...activePointers.values()][0];dragStart={...pos};dragLast={...pos};moved=true;}}
renderer.domElement.addEventListener('pointerup',releasePointer);renderer.domElement.addEventListener('pointercancel',releasePointer);renderer.domElement.addEventListener('lostpointercapture',e=>{if(activePointers.has(e.pointerId)){activePointers.delete(e.pointerId);clearSelection();}if(!activePointers.size)dragStart=null;});
function setInspectZoom(z){inspectZoom=clampZoom(z);camera.zoom=inspectZoom;camera.updateProjectionMatrix();}
renderer.domElement.addEventListener('wheel',e=>{if(!inspecting)return;e.preventDefault();setInspectZoom(inspectZoom*Math.exp(-e.deltaY*.001));},{passive:false});


let pageFlip=null;
function cancelPageFlip(){if(!pageFlip)return;clearTimeout(pageFlip.timer);pageFlip.animation.cancel();pageFlip.leaf.remove();pageFlip=null;$('game').classList.remove('catalog-turning');}
function turnCatalogPage(index,direction){
 if(pageFlip||!inspecting)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return showModel(index);
 const gameRect=$('game').getBoundingClientRect(),canvasRect=renderer.domElement.getBoundingClientRect();
 renderer.render(scene,camera);const snapshot=renderer.domElement.toDataURL('image/png');
 const leaf=document.createElement('div');leaf.className='book-turn-leaf';const heading=document.createElement('b');heading.textContent=products[inspectIndex].name;leaf.append(heading);const img=document.createElement('img');img.src=snapshot;img.alt='';leaf.append(img);$('catalog').append(leaf);
 const rect=leaf.getBoundingClientRect();img.style.cssText=`left:${canvasRect.left-rect.left}px;top:${canvasRect.top-rect.top}px;width:${canvasRect.width}px;height:${canvasRect.height}px`;
 leaf.style.transformOrigin=direction>0?'left center':'right center';$('game').classList.add('catalog-turning');
 const animation=leaf.animate([{transform:'perspective(1000px) rotateY(0deg)',opacity:1,filter:'brightness(1)'},{transform:`perspective(1000px) rotateY(${direction*-72}deg)`,opacity:1,filter:'brightness(.83)',offset:.52},{transform:`perspective(1000px) rotateY(${direction*-135}deg)`,opacity:0,filter:'brightness(.92)'}],{duration:560,easing:'cubic-bezier(.3,.05,.2,1)',fill:'forwards'});
 const state={leaf,animation,timer:setTimeout(()=>{if(pageFlip!==state)return;showModel(index,true);$('scene').animate([{opacity:.25,transform:`translateX(${direction*12}px)`},{opacity:1,transform:'translateX(0)'}],{duration:280,easing:'ease-out'});},220)};pageFlip=state;
 animation.finished.then(()=>{if(pageFlip===state){leaf.remove();pageFlip=null;$('game').classList.remove('catalog-turning');}}).catch(()=>{});
}
function showModel(index,turning=false){if(!turning)cancelPageFlip();setInspectZoom(1);inspectIndex=index;if(inspectObj)scene.remove(inspectObj);inspectObj=templates[index].clone();inspectObj.scale.setScalar((products[index].key==='prime-t1'?4.9:6.2)/products[index].size);inspectObj.rotation.set(.05,-.35,0);inspectObj.position.set(0,.8,0);scene.add(inspectObj);$('modelName').textContent=products[index].name;$('catalogPage').textContent=String(index+1).padStart(2,'0')+' / '+String(products.length).padStart(2,'0');$('catalogPrev').disabled=!templates.slice(0,index).some(Boolean);$('catalogNext').disabled=!templates.slice(index+1).some(Boolean);Array.from($('modelList').children).forEach((b,i)=>b.classList.toggle('active',i===index))}
// Keep the same WebGL canvas for inspection and gameplay, avoiding extra contexts.
$('catalogPrev').onclick=()=>{for(let i=inspectIndex-1;i>=0;i--)if(templates[i])return turnCatalogPage(i,-1);};
$('catalogNext').onclick=()=>{for(let i=inspectIndex+1;i<products.length;i++)if(templates[i])return turnCatalogPage(i,1);};
$('catalogButton').onclick=()=>{$('game').classList.add('catalog-open');$('catalogPaper').hidden=false;catalogFromHome=status==='home';if(catalogFromHome){homeStage.active=false;$('loading').hidden=true;$('game').classList.remove('home');resize();} $('closeCatalogLabel').textContent=catalogFromHome?'返回首页':'返回游戏';benchLabel.hidden=true;inspecting=true;paused=true;camera.position.set(4,3.5,7);camera.lookAt(0,.4,0);$('overlay').hidden=true;$('catalog').hidden=false;document.querySelector('.topbar').hidden=true;document.querySelector('.bottom').hidden=true;$('holding').hidden=true;items.forEach(i=>i.mesh.visible=false);kitchen.visible=false;scene.background=null;renderer.setClearColor(0,0);resize();$('modelList').innerHTML='';products.forEach((p,i)=>{let b=document.createElement('button');b.innerHTML=`${thumbnails[i]?`<img src="${thumbnails[i]}" alt="">`:""}${p.name}`;b.disabled=!templates[i];b.onclick=()=>showModel(i);$('modelList').append(b)});showModel(templates.findIndex(Boolean))};
$('closeCatalog').onclick=()=>{cancelPageFlip();if(new URLSearchParams(location.search).has('model')){location.href=location.pathname;return}inspecting=false;$('game').classList.remove('catalog-open');$('catalogPaper').hidden=true;resize();benchLabel.hidden=level!==2;camera.zoom=1;camera.updateProjectionMatrix();camera.position.set(0,15,5.6);camera.lookAt(0,.3,0);scene.remove(inspectObj);inspectObj=null;$('catalog').hidden=true;document.querySelector('.topbar').hidden=false;document.querySelector('.bottom').hidden=false;$('holding').hidden=false;items.forEach(i=>i.mesh.visible=true);kitchen.visible=true;scene.background=new THREE.Color(0x918c82);renderer.setClearColor(0x918c82,1);if(catalogFromHome){homeStage.active=true;$('loading').hidden=false;$('game').classList.add('home');resize();return;}showDialog('暂停一下',`已消除 ${removed} / ${total} 件产品`)};
document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelVoice();if(document.hidden&&['playing','pouring'].includes(status)&&!paused)showDialog('游戏已暂停','回来后继续抓！')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(inspecting)$('closeCatalog').click();else if(!$('overlay').hidden&&['playing','pouring'].includes(status))$('resume').click();else if(ready)$('pause').click()}});
function frame(t){requestAnimationFrame(frame);let dt=Math.min((t-lastT)/1000,.05);lastT=t;gameAudio.music(!document.hidden&&!inspecting&&(status==='home'||(!paused&&['playing','pouring'].includes(status))));if(!paused&&['playing','pouring'].includes(status)){world.step(1/60,dt,3);syncMeshes();if(status==='pouring')tickPour(dt);else timerAccum+=dt;if(timerAccum>=1){const seconds=Math.floor(timerAccum);timerAccum-=seconds;remaining=Math.max(0,remaining-seconds);$('time').textContent=Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');if(!remaining){playSound('timeout');status='lost';showDialog('时间到了！',`已经消除 ${removed} / ${total} 件产品`,'重新开始')}}}if(tossClock>0){tossClock=Math.max(0,tossClock-dt);const f=Math.sin((.6-tossClock)/.6*Math.PI);wok.position.y=f*.24;wok.rotation.x=f*.045;basket.position.y=f*.24;basket.rotation.x=f*.045;}if(inspecting&&inspectObj){if(!dragStart)inspectObj.rotation.y+=dt*.15;animateProduct(inspectObj,products[inspectIndex].key,t/1000);}if(!paused)for(const it of items){animateProduct(it.mesh,products[it.type].key,t/1000,it.id*1.7);}if(status==='home'&&!inspecting&&homeStage)homeStage.render(t/1000,dt);else renderer.render(scene,camera)}
load();

function reviveGame(text){if(status!=='lost'||!matchesRevival(text))return;if(remaining===0)remaining=180;else{const returned=tray.splice(0);for(const it of returned){items.push(it);scene.add(it.mesh);world.addBody(it.body);it.body.position.set((Math.random()-.5)*4,3+Math.random(),(Math.random()-.5)*4);it.body.velocity.setZero();it.body.wakeUp();}}status=pendingDeck.length?'pouring':'playing';paused=false;locked=false;timerAccum=0;$('overlay').hidden=true;$('time').textContent=Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');update();message('同济子豪兄牛逼！继续抓！');}
function matchesRevival(text){return text.replace(/[\s\p{P}]/gu,'')==='同济子豪兄牛逼';}
let voicePointer=null;
function voiceState(state){$('voice').dataset.state=state;$('voice').setAttribute('aria-pressed',String(state==='recording'));$('voice').disabled=state==='processing';}
function beginVoice(){if(status!=='lost'||revivalTimer)return;$('reviveResult').textContent='';gameAudio.unlock();voiceInput(text=>$('reviveStatus').textContent=text,text=>{if(status!=='lost')return;$('reviveResult').textContent='识别结果：'+text;if(matchesRevival(text)){$('reviveStatus').textContent='口令正确！即将继续游戏';playSound('revive');$('voice').disabled=true;revivalTimer=setTimeout(()=>{revivalTimer=0;if(status==='lost')reviveGame(text);},850);}else $('reviveStatus').textContent='口令未匹配，请重新按住说一次。';},voiceState);}
$('voice').addEventListener('pointerdown',e=>{if(e.button!==0||voicePointer!==null)return;e.preventDefault();voicePointer=e.pointerId;$('voice').setPointerCapture(e.pointerId);beginVoice();});
$('voice').addEventListener('pointerup',e=>{if(e.pointerId!==voicePointer)return;voicePointer=null;releaseVoice();if($('voice').dataset.state==='idle')$('reviveStatus').textContent='请按住，待麦克风就绪后说话。';});
$('voice').addEventListener('pointercancel',()=>{voicePointer=null;cancelVoice();});
$('voice').addEventListener('lostpointercapture',()=>{if(voicePointer!==null){voicePointer=null;cancelVoice();}});
$('voice').addEventListener('contextmenu',e=>e.preventDefault());
$('voice').addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();beginVoice();}});
$('voice').addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();releaseVoice();}});
