import {createPlayerStore} from './player-store.mjs';
import {saveRecording} from './recording-store.mjs';
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));try{process.loadEnvFile?.(path.join(root,'.env'));}catch(e){if(e.code!=='ENOENT')throw e;}
const port=Number(process.env.PORT||8081),key=process.env.DASHSCOPE_API_KEY,base=process.env.DASHSCOPE_BASE_URL,model='qwen3-asr-flash';
const recordingsDir=process.env.ASR_RECORDINGS_DIR||path.join(root,'recordings');
const recordPlayer=createPlayerStore(process.env.PLAYER_STATS_FILE||path.join(root,'analytics','players.json'));
const configured=()=>!!key&&!!base&&!base.includes('YOUR_');const busy=new Set(),last=new Map();
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),p=decodeURIComponent(url.pathname);if(p.startsWith('/api/')){const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`&&origin!==`https://${req.headers.host}`)return json(res,403,{error:'不允许跨站调用'});if(p==='/api/players'&&req.method==='POST'){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>1024)return json(res,413,{error:'请求过大'});chunks.push(chunk);}let data;try{data=JSON.parse(Buffer.concat(chunks).toString());}catch{return json(res,400,{error:'请求格式错误'});}const valid=x=>typeof x==='string'&&/^[a-zA-Z0-9-]{16,80}$/.test(x);if(!valid(data?.browserId)||(data.eventId!==undefined&&!valid(data.eventId)))return json(res,400,{error:'标识无效'});return json(res,200,await recordPlayer(data.browserId,data.eventId));}if(p==='/api/asr/status'&&req.method==='GET')return json(res,200,{configured:configured()});if(p!=='/api/asr'||req.method!=='POST')return json(res,404,{error:'接口不存在'});if(!configured())return json(res,503,{error:'尚未配置阿里云 API Key 和服务地址'});const ip=(['127.0.0.1','::1'].includes(req.socket.remoteAddress)&&req.headers['x-real-ip'])||req.socket.remoteAddress;if(busy.has(ip)||Date.now()-(last.get(ip)||0)<3000)return json(res,429,{error:'请稍后再试'});const endpoint=new URL(base);if(endpoint.protocol!=='https:'||!/(^|\.)aliyuncs\.com$/.test(endpoint.hostname))return json(res,503,{error:'阿里云服务地址配置不正确'});busy.add(ip);last.set(ip,Date.now());try{let size=0;const chunks=[];for await(const part of req){size+=part.length;if(size>2*1024*1024)return json(res,413,{error:'录音过长，请控制在 6 秒内'});chunks.push(part);}const audio=Buffer.concat(chunks);if(audio.length<44||audio.toString('ascii',0,4)!=='RIFF'||audio.toString('ascii',8,12)!=='WAVE')return json(res,400,{error:'需要 WAV 录音'});await saveRecording(recordingsDir,audio);const response=await fetch(base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content:[{type:'input_audio',input_audio:{data:'data:audio/wav;base64,'+audio.toString('base64')}}]}],stream:false,asr_options:{language:'zh',enable_itn:false}}),signal:AbortSignal.timeout(30000)});if(!response.ok)return json(res,502,{error:response.status===401?'阿里云密钥或地域不匹配':response.status===429?'阿里云额度或调用频率受限':'阿里云识别失败，请检查模型权限和余额'});const data=await response.json(),text=data.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())return json(res,502,{error:'没有识别到语音，请重试'});return json(res,200,{text});}finally{busy.delete(ip);}}
 // Only public game assets are served; never serve .env, source tools, CAD or documentation.
 const allowed=p==='/'||p==='/index.html'||p==='/抓个矽递-3D.html'||['/style.css','/game.js','/game-zones.js','/game-levels.js','/game-scenes.js','/container-physics.js','/home-stage.js','/product-visuals.js','/motion-controls.js','/sound-effects.js','/voice-input.js'].includes(p)||/^\/assets\/(models|textures|titles|audio|icons)\/[^/]+\.(glb|jpg|png|m4a|mp3)$/.test(p)||p==='/assets/favicon.svg'||/^\/node_modules\/(three|cannon-es)\/[\w/.-]+\.js$/.test(p);
 if(!allowed||p.split('/').some(x=>x.startsWith('.')))return json(res,404,{error:'不存在'});if(req.method!=='GET')return json(res,405,{error:'不支持该方法'});const filename=path.resolve(root,'.'+(p==='/'?'/index.html':p));if(!filename.startsWith(root+path.sep))return json(res,404,{error:'不存在'});const data=await fs.readFile(filename);const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.glb':'model/gltf-binary','.jpg':'image/jpeg','.png':'image/png','.m4a':'audio/mp4','.mp3':'audio/mpeg'};res.writeHead(200,{'Content-Type':mime[path.extname(filename)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(data);
 }catch(e){json(res,e.code==='ENOENT'?404:500,{error:e.name==='TimeoutError'?'识别超时，请重试':'请求失败，请稍后再试'});}});server.listen(port,'127.0.0.1',()=>console.log(`游戏服务：http://localhost:${port}（语音${configured()?'已配置':'待配置'}）`));
