import fs from 'node:fs';import {build} from 'esbuild';
const result=await build({entryPoints:['game.js'],bundle:true,format:'iife',minify:true,target:'es2022',write:false});
const textureData={'uno-q':'data:image/jpeg;base64,'+fs.readFileSync('assets/textures/uno-q.jpg').toString('base64')};
const titleData=Object.fromEntries(['products'].map(k=>[k,'data:image/png;base64,'+fs.readFileSync(`assets/titles/title-${k}.png`).toString('base64')]));
const iconData=Object.fromEntries(['campaign','stew','catalog','nvidia','hightorque','seeed','lerobot'].map(k=>[k,'data:image/png;base64,'+fs.readFileSync(`assets/icons/${k}.png`).toString('base64')]));
const catalogAudioData='data:audio/mpeg;base64,'+fs.readFileSync('assets/audio/catalog-shinian.mp3').toString('base64');
const audioData='data:audio/mp4;base64,'+fs.readFileSync('assets/audio/glue-rap.m4a').toString('base64');
const models=JSON.parse(fs.readFileSync('assets/model-sources/products.json'));const data={};for(const p of models)data[p.file.replace('.glb','')]='data:model/gltf-binary;base64,'+fs.readFileSync('assets/models/'+p.file).toString('base64');
let html=fs.readFileSync('index.html','utf8').replace('<link rel="stylesheet" href="style.css">','<style>'+fs.readFileSync('style.css','utf8')+'</style>').replace(/<script type="importmap">[\s\S]*?<\/script>/,'').replace('<script type="module" src="game.js"></script>',()=>'<script>window.SEEED_ICON_DATA='+JSON.stringify(iconData)+';window.SEEED_TITLE_DATA='+JSON.stringify(titleData)+';window.SEEED_AUDIO_DATA='+JSON.stringify(audioData)+';window.SEEED_CATALOG_AUDIO_DATA='+JSON.stringify(catalogAudioData)+';window.SEEED_MODEL_DATA='+JSON.stringify(data)+';window.SEEED_TEXTURE_DATA='+JSON.stringify(textureData)+';</script><script>'+result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script>');
html=html.replace('src="assets/titles/title-products.png"','src="'+titleData.products+'"');
for(const key of ['resume','restart','home','catalog'])html=html.replaceAll('assets/icons/pause-'+key+'.png','data:image/png;base64,'+fs.readFileSync('assets/icons/pause-'+key+'.png').toString('base64'));
for(const key of ['back','title','bookmark','next'])html=html.replaceAll('assets/icons/catalog-'+key+'.png','data:image/png;base64,'+fs.readFileSync('assets/icons/catalog-'+key+'.png').toString('base64'));
fs.writeFileSync('抓个矽递-3D.html',html);console.log('Offline HTML: '+Math.round(Buffer.byteLength(html)/1024/1024)+' MB');
