import fs from 'node:fs';import * as T from 'three';import {STLLoader} from 'three/addons/loaders/STLLoader.js';import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';import {XMLParser} from 'fast-xml-parser';
globalThis.FileReader=class{readAsArrayBuffer(b){b.arrayBuffer().then(x=>{this.result=x;this.onloadend?.()})}};
const base='assets/cad/tonypi/',xml=new XMLParser({ignoreAttributes:false,attributeNamePrefix:''}).parse(fs.readFileSync(base+'robot.xml','utf8')).mujoco;
const arr=x=>x?(Array.isArray(x)?x:[x]):[],vec=(s,f='0 0 0')=>(s||f).split(/\s+/).map(Number),assets=Object.fromEntries(arr(xml.asset.mesh).map(m=>[m.name,m])),loader=new STLLoader();let triangles=0;
function build(b){const group=new T.Group();group.name=b.name;group.position.fromArray(vec(b.pos));if(b.quat){const [w,x,y,z]=vec(b.quat);group.quaternion.set(x,y,z,w);}for(const g of arr(b.geom)){if(g.class!=='visual'||!g.mesh)continue;const asset=assets[g.mesh],buf=fs.readFileSync(base+asset.file),geo=loader.parse(buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength));geo.scale(...vec(asset.scale,'1 1 1'));triangles+=geo.attributes.position.count/3;
 const color=b.name.includes('ankle_roll')?'#c2c7ca':b.name==='torso'?'#ecefed':b.name.startsWith('head')?'#f0f1ed':b.name.includes('gripper')?'#e5e9e8':'#e5e9e8';
 const mesh=new T.Mesh(geo,new T.MeshStandardMaterial({color,roughness:.46,metalness:.25}));group.add(mesh);
 }
 // Servo dimensions and poses are provided by the CAD-based simulation assembly.
 for(const g of arr(b.geom).filter(g=>g.class==='internal'&&g.name.endsWith('_servo'))){const dims=vec(g.size);const mesh=new T.Mesh(new T.BoxGeometry(...dims.map(x=>x*2)),new T.MeshStandardMaterial({color:0x21252b,roughness:.5,metalness:.2}));mesh.position.fromArray(vec(g.pos));if(g.quat){const [w,x,y,z]=vec(g.quat);mesh.quaternion.set(x,y,z,w);}group.add(mesh);}
 if(b.name==='head_tilt'){const ring=new T.Mesh(new T.CylinderGeometry(.0095,.0095,.005,32),new T.MeshStandardMaterial({color:0x21242a,metalness:.4,roughness:.25}));ring.position.set(0,-.033,.005);group.add(ring);const glass=new T.Mesh(new T.CylinderGeometry(.0065,.0065,.0008,32),new T.MeshStandardMaterial({color:0x533744,metalness:.5,roughness:.15}));glass.position.set(0,-.036,.005);group.add(glass);}
 if(b.name==='torso'){const points=[[-.035,.279],[-.008,.279],[-.003,.29],[.003,.266],[.008,.279],[.035,.279]].map(([x,z])=>new T.Vector3(x,-.0428,z));const curve=new T.CurvePath();for(let i=1;i<points.length;i++)curve.add(new T.LineCurve3(points[i-1],points[i]));group.add(new T.Mesh(new T.TubeGeometry(curve,32,.0007,4,false),new T.MeshStandardMaterial({color:0x252b2d})));}
 for(const c of arr(b.body))group.add(build(c));return group;}
const root=new T.Group();for(const b of arr(xml.worldbody.body))root.add(build(b));root.rotation.x=-Math.PI/2;root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(root),sz=box.getSize(new T.Vector3());root.position.sub(box.getCenter(new T.Vector3()));const normalized=new T.Group();normalized.add(root);normalized.scale.setScalar(2/Math.max(...sz.toArray()));const data=await new GLTFExporter().parseAsync(normalized,{binary:true});fs.writeFileSync('assets/models/tonypi.glb',Buffer.from(data));console.log({triangles,bytes:data.byteLength,size:sz.toArray()});
