import assert from 'node:assert/strict';import {GameAudio} from '../sound-effects.js';
const starts=[];const param={setValueAtTime(v,t){assert.ok(Number.isFinite(v)&&Number.isFinite(t));},exponentialRampToValueAtTime(v,t){assert.ok(v>0&&Number.isFinite(t));},linearRampToValueAtTime(v,t){assert.ok(Number.isFinite(v)&&Number.isFinite(t));}};globalThis.window={AudioContext:class{constructor(){this.currentTime=1;this.state='running';this.destination={};}createGain(){return {gain:{...param},connect(){},disconnect(){}}}createOscillator(){return {frequency:param,connect(){},disconnect(){},start(t){starts.push(t)},stop(){}}}}};const audio=new GameAudio();audio.play('select');assert.equal(starts.length,0);audio.unlock();for(const event of ['select','clear','full','timeout','toss','remove','gather','shuffle']){const before=starts.length;audio.play(event);assert.ok(starts.length>before,event);const after=starts.length;audio.play(event);assert.equal(starts.length,after,'debounced '+event);}console.log('PASS: all 8 sound cues schedule valid envelopes after user activation; rapid duplicate cues are throttled');
const cues=[];audio.tone=(...args)=>cues.push(args);for(let i=0;i<12;i++)audio.play('drop',i);assert.equal(cues.length,12);assert.ok(cues[11][1]>cues[0][1]);const signatures=new Set();for(let i=0;i<24;i++){audio.last.clear();cues.length=0;audio.play('clear',i);signatures.add(JSON.stringify(cues));}assert.equal(signatures.size,24);
let plays=0,pauses=0;audio.track={paused:true,play(){plays++;this.paused=false;return Promise.resolve()},pause(){pauses++;this.paused=true}};audio.music(true);await new Promise(setImmediate);audio.music(true);assert.equal(plays,1);audio.music(false);assert.equal(audio.track.paused,true);audio.music(true);assert.equal(plays,2);await new Promise(setImmediate);audio.music(false);assert.ok(pauses>0);console.log('PASS: one cue per spawn, 24 unique clearing melodies, rap playback resumes and pauses without overlapping');
// A real gesture must retry even while the initial autoplay request is pending.
const retry=new GameAudio();let rejectAutoplay,retries=0;
retry.track={paused:true,muted:false,play(){retries++;if(retries===1)return new Promise((_,reject)=>{rejectAutoplay=reject});this.paused=false;return Promise.resolve()},pause(){this.paused=true}};
retry.music(true);await retry.unlock();assert.equal(retries,2);rejectAutoplay(new Error('Autoplay blocked'));await new Promise(setImmediate);assert.equal(retry.musicBlocked,false);assert.equal(retry.track.paused,false);assert.equal(retry.track.muted,false);console.log('PASS: homepage gesture retries pending autoplay; stale rejection cannot block music');
window.Audio=class{constructor(src){this.src=src;this.paused=true;}play(){this.paused=false;return Promise.resolve()}pause(){this.paused=true;}};
const piano=new GameAudio('assets/audio/catalog-yeyeye.mp3');audio.music(false);piano.music(true,true);await piano.unlock();await new Promise(setImmediate);assert.equal(piano.track.src,'assets/audio/catalog-yeyeye.mp3');assert.equal(piano.track.loop,true);assert.equal(piano.track.volume,.18);assert.equal(piano.track.paused,false);assert.equal(audio.track.paused,true);piano.music(false);assert.equal(piano.track.paused,true);cues.length=0;audio.play('catalog');assert.equal(cues.length,2);console.log('PASS: custom piano source loops, pauses on exit, and catalog switch cue plays');
const beforeInactiveUnlock=plays;await audio.unlock();await new Promise(setImmediate);assert.equal(plays,beforeInactiveUnlock);assert.equal(audio.track.paused,true);console.log('PASS: unlocking effects never starts inactive music or steals catalog playback');
